### ISSUE TITLE
Not loading M3U or Xtream streams

### ISSUE THREAD

**Issue by Firehand81** [Fredolx/open-tv#176]
If I try to log in with Xtream codes, I get error. From log file: 
**"[ERROR] error decoding response body

Caused by:
    expected value at line 1 column 1"**

Correcting server address, this changes to:
**"[ERROR] error decoding response body

Caused by:
    EOF while parsing a value at line 1 column 0"**

If I use M3U URL, I get success message (can even successfully refresh) but no Live streams or series etc. appearing or searchable and no mention at logs.

Both Xtream codes and m3u url work fine with other IPTV apps and even my TVs IPTV app.

**Comment by Fredolx** [comment]
Hi

Can you send me your xtream logins by e-mail?

frederic.lachapelle7@gmail.com

**Comment by Fredolx** [comment]
Thank you, I was able to find the issue. Your provider needs a user agent to be provided for the xtream requests to be accepted. I will be adding an option to specify a user agent with some sane defaults.

**Comment by Fredolx** [comment]
Fixed with 1.6.0

**Comment by g0ldyy** [comment]
@Fredolx no it's not, still getting this error:

        error decoding response body

Caused by:
    missing field `episodes` at line 1 column 2

**Comment by Fredolx** [comment]
Thanks Goldy, this will be fixed. I was working on it when JayWore made #190 but he seems to have deleted his account and so the issue also disappeared.

**Comment by lee-js** [comment]
I am also having this problem. I do not see an option to add a useragent in v1.7
